In [1]:
import sys
from pathlib import Path
import pandas as pd
import numpy as np

sys.path.append(str(Path.cwd().parent / "scripts"))

import config
import cleaning as clean

In [ ]:
df = pd.read_csv(config.DATA_RAW / "financials.csv")
df["Company"].unique()
# df["Section"].unique()
# df

<StringArray>
['P&L', 'BalanceSheet', 'CashFlow']
Length: 3, dtype: str

In [3]:
companies = [
    "HUL",
    "ITC",
    "Dabur",
    "Marico",
    "Colgate",
    "Nestle",
    "Godrej",
    "Emami"
]
companies = clean.split_by_column(df, "Company")
companies["Nestle"].head(10)

split_by_column('Company'): 8 groups from 2688 rows
  HUL           336 rows
  ITC           336 rows
  Dabur         336 rows
  Marico        336 rows
  Colgate       336 rows
  Nestle        336 rows
  Godrej        336 rows
  Emami         336 rows

     LineItem  Period    Value Unit ValueRaw Company Section
1680    Sales  FY2015   8175.0   Cr    8,175  Nestle     P&L
1681    Sales  FY2016   9141.0   Cr    9,141  Nestle     P&L
1682    Sales  FY2017  10010.0   Cr   10,010  Nestle     P&L
1683    Sales  FY2018  11292.0   Cr   11,292  Nestle     P&L
1684    Sales  FY2019  12369.0   Cr   12,369  Nestle     P&L
1685    Sales  FY2020  13350.0   Cr   13,350  Nestle     P&L
1686    Sales  FY2021  14741.0   Cr   14,741  Nestle     P&L
1687    Sales  FY2022  16897.0   Cr   16,897  Nestle     P&L
1688    Sales  FY2023  19126.0   Cr   19,126  Nestle     P&L
1689    Sales  FY2024  24394.0   Cr   24,394  Nestle     P&L

In [4]:
# drop the now-redundant grouping column from each company sub_df (logic in cleaning.py)
for company, sub_df in companies.items():
    clean.drop_column(sub_df, "Company")
    clean.drop_column(sub_df, "ValueRaw")

companies["Nestle"].head(10)

     LineItem  Period    Value Unit Section
1680    Sales  FY2015   8175.0   Cr     P&L
1681    Sales  FY2016   9141.0   Cr     P&L
1682    Sales  FY2017  10010.0   Cr     P&L
1683    Sales  FY2018  11292.0   Cr     P&L
1684    Sales  FY2019  12369.0   Cr     P&L
1685    Sales  FY2020  13350.0   Cr     P&L
1686    Sales  FY2021  14741.0   Cr     P&L
1687    Sales  FY2022  16897.0   Cr     P&L
1688    Sales  FY2023  19126.0   Cr     P&L
1689    Sales  FY2024  24394.0   Cr     P&L

In [5]:
companies = {name: clean.split_by_column(sub_df, "Section") for name, sub_df in companies.items()}
companies["Nestle"]["P&L"].head(10)

split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows
split_by_column('Section'): 3 groups from 336 rows
  P&L           144 rows
  BalanceSheet  120 rows
  CashFlow       72 rows

     LineItem  Period    Value Unit Section
1680    Sales  FY2015   8175.0   Cr     P&L
1681    Sales  FY2016   9141.0   Cr     P&L
1682    Sales  FY2017  10010.0   Cr     P&L
1683    Sales  FY2018  11292.0   Cr     P&L
1684    Sales  FY2019  12369.0   Cr     P&L
1685    Sales  FY2020  13350.0   Cr     P&L
1686    Sales  FY2021  14741.0   Cr     P&L
1687    Sales  FY2022  16897.0   Cr     P&L
1688    Sales  FY2023  19126.0   Cr     P&L
1689    Sales  FY2024  24394.0   Cr     P&L

In [6]:
# drop the redundant Section column from every innermost sub_df (logic in cleaning.py)
for company, sections in companies.items():
    for section, sub_df in sections.items():
        clean.drop_column(sub_df, "Section")

companies["Nestle"]["P&L"].head(10)

     LineItem  Period    Value Unit
1680    Sales  FY2015   8175.0   Cr
1681    Sales  FY2016   9141.0   Cr
1682    Sales  FY2017  10010.0   Cr
1683    Sales  FY2018  11292.0   Cr
1684    Sales  FY2019  12369.0   Cr
1685    Sales  FY2020  13350.0   Cr
1686    Sales  FY2021  14741.0   Cr
1687    Sales  FY2022  16897.0   Cr
1688    Sales  FY2023  19126.0   Cr
1689    Sales  FY2024  24394.0   Cr

In [7]:
# add key = "<LineItem>_<Period>" (e.g. 'Sales_FY2024') to every innermost sub_df
for company, sections in companies.items():
    for section, sub_df in sections.items():
        clean.add_key_column(sub_df)

companies["Nestle"]["P&L"].head(10)

     LineItem  Period    Value Unit           key
1680    Sales  FY2015   8175.0   Cr  Sales_FY2015
1681    Sales  FY2016   9141.0   Cr  Sales_FY2016
1682    Sales  FY2017  10010.0   Cr  Sales_FY2017
1683    Sales  FY2018  11292.0   Cr  Sales_FY2018
1684    Sales  FY2019  12369.0   Cr  Sales_FY2019
1685    Sales  FY2020  13350.0   Cr  Sales_FY2020
1686    Sales  FY2021  14741.0   Cr  Sales_FY2021
1687    Sales  FY2022  16897.0   Cr  Sales_FY2022
1688    Sales  FY2023  19126.0   Cr  Sales_FY2023
1689    Sales  FY2024  24394.0   Cr  Sales_FY2024

In [12]:
# reshape each innermost sub_df to wide: LineItem -> columns, Period(12) -> rows, Value -> cells
# (no period filter -> keep all 12 periods FY2015..FY2026; logic in cleaning.py)
wide = {company: {section: clean.pivot_line_items(sub_df)
                  for section, sub_df in sections.items()}
        for company, sections in companies.items()}

wide["Nestle"]["BalanceSheet"]

pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items
pivot_line_items: 12 periods x 12 line items
pivot_line_items: 12 periods x 10 line items
pivot_line_items: 12 periods x 6 line items

,Borrowings,CWIP,Equity Capital,Fixed Assets,Investments,Other Assets,Other Liabilities,Reserves,Total Assets,Total Liabilities
Period,,,,,,,,,,
FY2015,18.0,231.0,96.0,2898.0,1325.0,1633.0,3251.0,2721.0,6086.0,6086.0
FY2016,33.0,188.0,96.0,2730.0,1756.0,2136.0,3495.0,3186.0,6810.0,6810.0
FY2017,35.0,94.0,96.0,2616.0,1979.0,2673.0,3907.0,3324.0,7363.0,7363.0
FY2018,35.0,105.0,96.0,2401.0,2658.0,2924.0,4379.0,3577.0,8088.0,8088.0
FY2019,189.0,143.0,96.0,2341.0,1751.0,2937.0,5065.0,1822.0,7173.0,7173.0
FY2020,147.0,639.0,96.0,2179.0,1464.0,3618.0,5733.0,1923.0,7900.0,7900.0
FY2021,266.0,246.0,96.0,2995.0,774.0,4219.0,6021.0,1850.0,8234.0,8234.0
FY2022,271.0,358.0,96.0,3044.0,778.0,4799.0,6249.0,2363.0,8979.0,8979.0
FY2023,271.0,358.0,96.0,3044.0,778.0,4799.0,6249.0,2363.0,8979.0,8979.0
FY2024,345.0,1742.0,96.0,3460.0,464.0,4857.0,6838.0,3244.0,10523.0,10523.0
FY2025,1167.0,1173.0,96.0,5474.0,706.0,4972.0,7040.0,4021.0,12324.0,12324.0
FY2026,444.0,507.0,193.0,6290.0,706.0,5854.0,7604.0,5116.0,13357.0,13357.0

In [ ]:
# save each wide frame -> data/cleaned/<Company>/<Section>.csv  (8 folders x 3 files = 24; logic in cleaning.py)
clean.save_wide(wide, config.DATA_CLEANED)